export const GET_USER_BATCHED = `
query($token:String!,$field:String!,$id:String!){
    getUsersByField(token:$token,field:$field,id:$id){
        id
        email
        lada
        phoneNumber
        usersProfile{
            taxo
            status
            name
            accounts{
                id
                clientId
                externalId
                firstName
                lastName
                middleName
                secondLastName
                status
                alias
                pin
                term
                feeCardVirtual
                feeCardPhysical
                currency
                gender
                birthday
                nationalId
                otherNationalId
                avatarImage
                countryCode
                customerId
                address{
                    status
                    id
                    city
                    suburb
                    country
                    state
                    street
                    number
                    typeAddress
                    zipCode
                    shortName
                }
                bankInformation{
                    id
                    bankName
                    routingNumber
                    accountNumber
                }
                kyc{
                    id
                    typeIdentification
                    frontId
                    backId
                    kycid
                    faceId
                    documentId
                    status
                }
                securityQuestion{
                    id
                    answer
                    question
                }
            }
        }
    }
}`;

export const SET_FILE = `
mutation($token:String!,$fileName:String!,$file64:String!){
  setFile(token:$token,fileName:$fileName,file64:$file64)
}`;


export const VALIDATE_SESSION_QUERY = `
query($token:String!){
  getValidateSession(token:$token){
    token
    uuid
    timeOut
    locked
  }
}`;


