export const GET_USER_BATCHED = `
query($token:String!,$field:String!,$id:String!){
  getUsersByField(token:$token,field:$field,id:$id)
  {
      id
      email
      phoneNumber
      lada
      clients {
        id
        externalId
        status
        activationDate
        officeId
        firstName
        middleName
        lastName
        fullName
        displayName
        mobileNo
        dateOfBirth
        emailAddress
        statusPayroll 
        account {
          id
          accountNo
          externalId
          clientId
          groupId
          currencyCode
          balance {
            year
            account
            deposit
            withdrawal
            total
            currency
          }
          transactions{
            id
            accountId 
            transactionDate
            type
            amount
            finalBalance
            currencyCode
            exchageRate
            createdDate
            note{
              id
              clientId
              groupId
              accountId
              transactionId
              noteDescription
            }
          } 
        }
        companies {
          id 
          pathLogo 
          name 
          feePhysicalCard
        }
      }
      usersProfile
      {
          userID
          id
          status
          name
          accountId
          roleId
          accounts
          {
              id
              term
              status
              firstName
              avatarImage
              lastName
              secondLastName
              phoneNumber
              middleName
              email
              clientId
              currency
              gender
              alias
              birthday
              nationalId
              otherNationalId
              countryCode
              externalId
              pin
              customerId
              isComplete
              address
              {
                  id
                  city
                  suburb
                  country
                  state
                  street
                  number
                  typeAddress
                  zipCode
                  shortName
                  isComplete
              }
                kyc{
                  id
                  typeIdentification
                  frontId
                  backId
                  kycid
                  faceId
                  documentId
                  status
                  isComplete
                }
                bankInformation
                {
                  id
                  bankName
                  routingNumber
                  accountNumber
                }
          }

      }
  }
}`;

export const SET_FILE = `
mutation($token:String!,$fileName:String!,$file64:String!){
  setFile(token:$token,fileName:$fileName,file64:$file64)
}`;


export const VALIDATE_SESSION_QUERY =`
query($token:String!){
  getValidateSession(token:$token){
    token
    uuid
    timeOut
    locked
  }
}`;


