export default {
  creditInfo: {
    level           : 3,
    available       : 3,
    maxAmount       : 2500,
    contractedAmount: 1250.3,
    contracted      : 2
  },
  availableCredits: [
    {
      level             : 3,
      amount            : 13500,
      provider          : 'Créditos Savvy',
      providerDetail    : 'Lorem Ipsum',
      numberOfPayments  : 3,
      paymentsFrequency : 'Quincenas',
      interestPercentage: 5,
      interest          : 175,
      iva               : 26.25,
      total             : 13900,
      installmentsAmount: 1600,
      coin              : 'MXN',
    },
    {
      level             : 3,
      amount            : 8000,
      provider          : 'Créditos Savvy',
      providerDetail    : 'Lorem Ipsum',
      numberOfPayments  : 10,
      paymentsFrequency : 'Quincenas',
      interestPercentage: 0,
      interest          : 175,
      iva               : 26.25,
      total             : 8030,
      installmentsAmount: 2890,
      coin              : 'MXN',
    },
    {
      level             : 3,
      amount            : 3500,
      provider          : 'Créditos Savvy',
      providerDetail    : 'Lorem Ipsum',
      numberOfPayments  : 18,
      paymentsFrequency : 'Quincenas',
      interestPercentage: 10,
      interest          : 175,
      iva               : 26.25,
      total             : 3635,
      installmentsAmount: 2312,
      coin              : 'MXN',
    }
  ],
  hiredCredits: [
    {
      level             : 3,
      amount            : 13500,
      provider          : 'Créditos Savvy',
      numberOfPayments  : '4/6',
      paymentsFrequency : 'Quincenas',
      interestPercentage: 5,
      interest          : 175,
      iva               : 26.25,
      total             : 13900,
      installmentsAmount: 1600,
      coin              : 'MXN',
      detline           : '11/03/2019',
      detail            : 'Elecreódomésticos Liverpool lorem Ipsum dolor sit',
      status            : 'pay'
    },
    {
      level             : 3,
      amount            : 8000,
      provider          : 'Créditos Savvy',
      numberOfPayments  : '3/6',
      paymentsFrequency : 'Quincenas',
      interestPercentage: 0,
      interest          : 175,
      iva               : 26.25,
      total             : 8030,
      installmentsAmount: 2890,
      coin              : 'MXN',
      detline           : '15/02/2020',
      detail            : 'Elecreódomésticos Liverpool lorem Ipsum dolor sit',
      status            : 'pending'
    },
    {
      level             : 3,
      amount            : 3500,
      provider          : 'Créditos Savvy',
      numberOfPayments  : '2/6',
      paymentsFrequency : 'Quincenas',
      interestPercentage: 10,
      interest          : 175,
      iva               : 26.25,
      total             : 3635,
      installmentsAmount: 2312,
      coin              : 'MXN',
      detline           : '05/08/2022',
      detail            : 'Elecreódomésticos Liverpool lorem Ipsum dolor sit',
      status            : 'warning'
    }
  ]
};
